version: 2

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: supactl
    main: ./main.go
    binary: supactl
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X github.com/qubitquilt/supactl/cmd.version={{.Version}}
    flags:
      - -trimpath

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - SUPACTL_README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'README'
      - Merge pull request
      - Merge branch
  groups:
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: 'Enhancements'
      regexp: "^.*enhance[(\\w)]*:+.*$"
      order: 2
    - title: 'Others'
      order: 999

release:
  github:
    owner: qubitquilt
    name: supactl
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
  footer: |
    ## Installation

    ### Linux/macOS
    ```bash
    # Download and extract
    curl -L https://github.com/qubitquilt/supactl/releases/download/{{ .Tag }}/{{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch "amd64" }}x86_64{{ else }}{{ .Arch }}{{ end }}.tar.gz | tar xz

    # Move to PATH
    sudo mv supactl /usr/local/bin/
    ```

    ### Windows
    Download the `.zip` file, extract it, and add the binary to your PATH.

    ---

    **Full Changelog**: https://github.com/qubitquilt/supactl/compare/{{ .PreviousTag }}...{{ .Tag }}

brews:
  - repository:
      owner: qubitquilt
      name: homebrew-tap
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Formula
    homepage: https://github.com/qubitquilt/supactl
    description: "CLI for managing self-hosted Supabase instances"
    license: "MIT"
    install: |
      bin.install "supactl"
    test: |
      system "#{bin}/supactl", "--version"
